Language: "en_US"
CheckUpdate: true
#1.8-1.8.8 Particle list: BARRIER; BLOCK_CRACK; BLOCK_DUST; CLOUD; CRIT; CRIT_MAGIC; DRIP_LAVA; DRIP_WATER; ENCHANTMENT_TABLE; EXPLOSION_HUGE;
#EXPLOSION_LARGE; EXPLOSION_NORMAL; FIREWORKS_SPARK; FLAME; FOOTSTEP; HEART; ITEM_CRACK; ITEM_TAKE; LAVA; MOB_APPEARANCE; NOTE; PORTAL;
#REDSTONE; SLIME; SMOKE_LARGE; SMOKE_NORMAL; SNOW_SHOVEL; SNOWBALL; SPELL; SPELL_INSTANT; SPELL_MOB; SPELL_MOB_AMBIENT; SPELL_WITCH; SUSPENDED;
#SUSPENDED_DEPTH; TOWN_AURA; VILLAGER_ANGRY; VILLAGER_HAPPY; WATER_BUBBLE; WATER_DROP; WATER_SPLASH; WATER_WAKE;

#1.9.2-1.9.4 Particle list: BARRIER; BLOCK_CRACK; BLOCK_DUST; CLOUD; CRIT; CRIT_MAGIC; DAMAGE_INDICATOR; DRAGON_BREATH; DRIP_LAVA; DRIP_WATER;
#ENCHANTMENT_TABLE; END_ROD; EXPLOSION_HUGE; EXPLOSION_LARGE; EXPLOSION_NORMAL; FIREWORKS_SPARK; FLAME; FOOTSTEP; HEART; ITEM_CRACK; ITEM_TAKE;
#LAVA; MOB_APPEARANCE; NOTE; PORTAL; REDSTONE; SLIME; SMOKE_LARGE; SMOKE_NORMAL; SNOW_SHOVEL; SNOWBALL; SPELL; SPELL_INSTANT; SPELL_MOB;
#SPELL_MOB_AMBIENT; SPELL_WITCH; SUSPENDED; SUSPENDED_DEPTH; SWEEP_ATTACK; TOWN_AURA; VILLAGER_ANGRY; VILLAGER_HAPPY; WATER_BUBBLE; WATER_DROP;
#WATER_SPLASH; WATER_WAKE;

#1.10.2 Particle list: BARRIER; BLOCK_CRACK; BLOCK_DUST; CLOUD; CRIT; CRIT_MAGIC; DAMAGE_INDICATOR; DRAGON_BREATH; DRIP_LAVA; DRIP_WATER;
#ENCHANTMENT_TABLE; END_ROD; EXPLOSION_HUGE; EXPLOSION_LARGE; EXPLOSION_NORMAL; FALLING_DUST; FIREWORKS_SPARK; FLAME; FOOTSTEP; HEART;
#ITEM_CRACK; ITEM_TAKE; LAVA; MOB_APPEARANCE; NOTE; PORTAL; REDSTONE; SLIME; SMOKE_LARGE; SMOKE_NORMAL; SNOW_SHOVEL; SNOWBALL; SPELL;
#SPELL_INSTANT; SPELL_MOB; SPELL_MOB_AMBIENT; SPELL_WITCH; SUSPENDED; SUSPENDED_DEPTH; SWEEP_ATTACK; TOWN_AURA; VILLAGER_ANGRY;
#VILLAGER_HAPPY; WATER_BUBBLE; WATER_DROP; WATER_SPLASH; WATER_WAKE;

#1.11.2-1.12.2 Particle list: BARRIER; BLOCK_CRACK; BLOCK_DUST; CLOUD; CRIT; CRIT_MAGIC; DAMAGE_INDICATOR; DRAGON_BREATH; DRIP_LAVA; DRIP_WATER;
#ENCHANTMENT_TABLE; END_ROD; EXPLOSION_HUGE; EXPLOSION_LARGE; EXPLOSION_NORMAL; FALLING_DUST; FIREWORKS_SPARK; FLAME; FOOTSTEP; HEART;
#ITEM_CRACK; ITEM_TAKE; LAVA; MOB_APPEARANCE; NOTE; PORTAL; REDSTONE; SLIME; SMOKE_LARGE; SMOKE_NORMAL; SNOW_SHOVEL; SNOWBALL; SPELL;
#SPELL_INSTANT; SPELL_MOB; SPELL_MOB_AMBIENT; SPELL_WITCH; SPIT; SUSPENDED; SUSPENDED_DEPTH; SWEEP_ATTACK; TOTEM; TOWN_AURA; VILLAGER_ANGRY;
#VILLAGER_HAPPY; WATER_BUBBLE; WATER_DROP; WATER_SPLASH; WATER_WAKE;

#1.13-1.13.2 Particle list: BARRIER; BLOCK_CRACK; BLOCK_DUST; CLOUD; CRIT; CRIT_MAGIC; DAMAGE_INDICATOR; DRAGON_BREATH; DRIP_LAVA; DRIP_WATER;
#ENCHANTMENT_TABLE; END_ROD; EXPLOSION_HUGE; EXPLOSION_LARGE; EXPLOSION_NORMAL; FIREWORKS_SPARK; FLAME; FOOTSTEP; HEART; ITEM_CRACK
#ITEM_TAKE; LAVA; MOB_APPEARANCE; NOTE; PORTAL; REDSTONE; SLIME; SMOKE_LARGE; SMOKE_NORMAL; SNOW_SHOVEL; SNOWBALL; SPELL; SPELL_INSTANT;
#SPELL_MOB; SPELL_MOB_AMBIENT; SPELL_WITCH; SUSPENDED; SUSPENDED_DEPTH; SWEEP_ATTACK; TOWN_AURA; VILLAGER_ANGRY; VILLAGER_HAPPY; WATER_BUBBLE;
#WATER_DROP; WATER_SPLASH; WATER_WAKE;
Particle: "VILLAGER_HAPPY"
